### ISSUE TITLE
Delete button

### ISSUE THREAD

**Issue by pabloguerrez** [jameslkingsley/nova-media-library-field#1]
Hey,
nice field, very usefull! Sadly, the delete button is not shown.

**Comment by jameslkingsley** [comment]
Currently waiting on https://github.com/laravel/nova-issues/issues/409

**Comment by jameslkingsley** [comment]
While waiting on this issue, I just pushed some changes that implement a new `Images` field. This field will let you see all media associated with the resource and delete each media record. On deletion media-library will handle cleaning up any of the files left behind so you don't have to worry about that.

**Comment by shirshak55** [comment]
I think laravel nova bugs will take too much time to be fixed . Is there no hacky way to solve it?

**Comment by jameslkingsley** [comment]
@shirshak55 Using this packages `Images` field on your resource will give you a panel of all media for that resource, with delete buttons for each.

**Comment by jameslkingsley** [comment]
Just tagged a release that adds the delete button, and a custom route to delete the underlying media library resource. It's somewhat experimental so let me know if you run into any issues.
