### ISSUE TITLE
Image field needs a value to allow the form to be submitted

### ISSUE THREAD

**Issue by Elhebert** [jameslkingsley/nova-media-library-field#10]
When trying to create or update a resource without submitting an image (thus with an empty Image field), nothing happen and I got this error in the console:

```
Unhandled promise rejection TypeError: "e.t0.response is undefined, can't access property "status" of it"
```

My code looks like this:
```php
Image::make('Logo')
    ->usingConversion('optimized')
    ->toMediaCollection('logo'),
```

Any idea on what could cause this?

**Comment by jameslkingsley** [comment]
Can you post the stack trace please?

**Comment by jameslkingsley** [comment]
Ah wait this is client-side, my bad. I haven't seen this error on my end

**Comment by Elhebert** [comment]
Just saw that I was still using the 1.0.0 of Nova for that particular project 😱

Gonna update later today or on Monday and see if it was a nova related issue that is now fixed.

**Comment by jameslkingsley** [comment]
If you find this is still broken feel free to re-open the issue.
