### ISSUE TITLE
Ability to add other attachment like PDF, mp4?

### ISSUE THREAD

**Issue by shirshak55** [jameslkingsley/nova-media-library-field#11]
I think laravel medialibrary if for handling media not just image. So I think we can support it and just display appropriate thumbnail like pdf icon for pdf etc ?

And thanks for this awesome package :)

**Comment by jameslkingsley** [comment]
I saw on Twitter that Spatie is working on their own Nova media library package, so I think for the time being this package will stay as is, and then when their package is released this one will be depreciated.

**Comment by jameslkingsley** [comment]
Seemed pretty simple and I needed a generic file field too, so I just added that and refactored the code a bit. Check the new release (breaking change) on how to update.
