### ISSUE TITLE
Help regarding example

### ISSUE THREAD

**Issue by shirshak55** [jameslkingsley/nova-media-library-field#12]
Suppose we want to have two types of file one is video and another is cover image for that video. So we would like to store cover image as cover image collection and video as video collection so that we can query it easily later. And each model can have only 1 cover image and only 1 video no more than that how would we accomplish it?

I tried like this:

```
            File::make('Video'),

            Image::make('Cover Image')
                ->usingConversion('thumb')
                ->preservingOriginal()
                ->toMediaCollection('cover_image'),
```

according to read me we can use``` public function registerMediaCollections()``` but it will be problematic if we got two media isn't it?

**Comment by jameslkingsley** [comment]
That's not handled by this package, that's part of media library itself, see https://docs.spatie.be/laravel-medialibrary/v7/working-with-media-collections/defining-media-collections

**Comment by shirshak55** [comment]
So how do we solve this ?
