### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ghost** [jameslkingsley/nova-media-library-field#13]
not quite understand the principle of work.

I have photoreports, every photo report has a set of photographs.

in the photoreports I add:
use Kingsley \ NovaMediaLibrary \ Fields \ Images;
and in the field function:
Images :: make ('photos'),

it turns out something like that.
![default](https://user-images.githubusercontent.com/32259003/45747924-579dda80-bc18-11e8-8726-d7b86075bf2e.png)

what am I doing wrong?

**Comment by jameslkingsley** [comment]
Don't pass any arguments to `Images::make()`, just use `Images::make()`.
