### ISSUE TITLE
Only first ever uploaded image is used

### ISSUE THREAD

**Issue by ashupp** [jameslkingsley/nova-media-library-field#2]
Hi, i like this field very much.

On my fresh installed system i have the behaviour that only the first ever uploaded image per Object is displayed.

I have changed the fillAttributeFromRequest so any collection for this model is cleared before a new one is added.
Is this a Bug or am i doing / did understand something wrong?

...
        $model->clearMediaCollection('myCollectionName');
        $query = $model->addMedia($request[$requestAttribute]);
...

Best regards, Alex

**Comment by jameslkingsley** [comment]
This package currently only supports single file uploading. The frontend setup would need to change quite a bit to support multi-file upload. It's something I will likely implement in the future.

**Comment by jameslkingsley** [comment]
If you're not too bothered by the frontend not displaying all images, then I think this would work as an override for `fillAttributeFromRequest`:

```php
$query = $model->addAllMediaFromRequest();
```

**Comment by ashupp** [comment]
Hi and thank you for your replies and your hints.
It could be that i described the problem misreadingly in the first place.

This are my actual steps:

1. Adding the media-libary field to nova as described in the doc
2. Uploading an image via nova
3. Uploaded image is added to db and shown on the nova object view page
4. Uploading an other image via nova to the same object

Expected: The first uploaded image is replaced by the second uploaded image and the last uploaded image is shown.
Actual: The first uploaded image is shown no matter how much other images i upload after that. They are all stored in the db but only the first uploaded image is shown.

So i actually do not want multi upload - i want only to show the newest file.

Best regards, Alex

**Comment by jameslkingsley** [comment]
Ah okay, in that case you need to specify that for your media collection on your model such as:

```php
public function registerMediaCollections()
{
    $this
        ->addMediaCollection('logo')
        ->singleFile();
}
```

The `singleFile()` tells media library to clear it out when updating the collection.

**Comment by ashupp** [comment]
Thank you for your response. This clears so much up in my mind. And i now understand how it works together.

So its not a bug or a missing feature in your field. 

Thank you for providing help! You are great and your project also!
