### ISSUE TITLE
Media::hasGeneratedConversion() must be string, not array.

### ISSUE THREAD

**Issue by tanthammar** [jameslkingsley/nova-media-library-field#20]
I was unable to load index view after adding "nova-media-library" fields to my resource.
Got this error:
![image](https://user-images.githubusercontent.com/21239634/48956703-cb2fd100-ef54-11e8-915f-29fc323430f9.png)

Solved it by changing **row 87** in **Image.php** from this:
```
$conversion = $this->meta()['usingConversion'] ?? [];
```
To this:
```
$conversion = $this->meta()['usingConversion'] ?? '';
```

**Comment by jameslkingsley** [comment]
This should work now on 1.4.0.
