### ISSUE TITLE
How can I downlaod the uploaded file from the details page

### ISSUE THREAD

**Issue by yatinB07** [jameslkingsley/nova-media-library-field#25]
Hi,
@jameslkingsley @ebess 
I used File field for upload the pdf file with this package. The upload process is working fine, In the view page, it also shows me the name of the uploaded file. but how can I get the download button as the default File field offers? 
here is the code
`use Kingsley\NovaMediaLibrary\Fields\File;`
`...`
`File::make('File', 'activity_attachment');`
`...`

As per Laravel nova File field, if I used "storeOriginalName" this method with the File field then it can automatically show the download button.

**Comment by jameslkingsley** [comment]
I don't think there's any way to do this at the moment, sorry.
