### ISSUE TITLE
Single Image handling

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [jameslkingsley/nova-media-library-field#30]
I am finding the 'collection' approach to single image handling strange.

If I have a model with multiple image fields, and I want them to all only allow a single image per field, I have to make a bunch of different collections? This makes no sense to me, since I want all the image fields to draw from the same collection, but not to allow each individual field to select more than one item _from_ the collection in question.

Am I just misunderstanding the docs, or is creating a bunch of separate collections the only way make a model have multiple single selection only image fields?

**Comment by jameslkingsley** [comment]
Please consider using [this package](https://github.com/ebess/advanced-nova-media-library) instead as it's actively maintained and will probably support your use case
