### ISSUE TITLE
Image not showing on update screen

### ISSUE THREAD

**Issue by nkootstra** [jameslkingsley/nova-media-library-field#6]
<img width="1009" alt="screen shot 2018-09-10 at 18 19 00" src="https://user-images.githubusercontent.com/545768/45310261-145faf80-b526-11e8-8186-aa3a5e7f9dd5.png">
<img width="931" alt="screen shot 2018-09-10 at 18 18 47" src="https://user-images.githubusercontent.com/545768/45310268-16297300-b526-11e8-9f01-01fb3521441a.png">

It works fine on the index and detail page.

**Comment by jameslkingsley** [comment]
Should be working in 1.2.1 now!

**Comment by nkootstra** [comment]
It works.
