### ISSUE TITLE
Support Nova Image Cropper

### ISSUE THREAD

**Issue by shirshak55** [jameslkingsley/nova-media-library-field#9]
And is it possible to add nova cropper which is already available and live preview when user upload image

**Comment by jameslkingsley** [comment]
Just tagged a release for the image size and preview. Will look into the cropper package at some point.

**Comment by shirshak55** [comment]
@jameslkingsley have you checked nova cropper package? I think we can import idea from there

**Comment by jameslkingsley** [comment]
I briefly looked at it, implementing something similar for this package would require quite a lot of frontend work which I don't have time for at the moment. A PR for this would be welcome, as long as it's configurable by the user.

**Comment by jameslkingsley** [comment]
See response to #11
